In [1]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
%matplotlib inline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.compose import ColumnTransformer
# for Classifcation
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, \
    precision_recall_fscore_support,precision_score,recall_score,classification_report
# for Regression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score,\
explained_variance_score, max_error, median_absolute_error
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split, GridSearchCV,RandomizedSearchCV
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
import lazypredict
from lazypredict.Supervised import LazyClassifier
from lazypredict.Supervised import LazyRegressor
#from pycaret.regression import *
from pycaret.classification import *
#from pycaret.clustering import *
from skimpy import skim
from summarytools import dfSummary
import sweetviz as sv
import statsmodels.api as sm
import missingno as msno
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="dask")


In [2]:
df=pd.read_csv(r"E:\Machine Project\Cleand_weather_data.csv")

In [3]:
df.head(20)

date location  minimum_temp  maximum_temp  rain_fall  \
0   2008-12-01   Albury         13.40         22.90       0.60   
1   2008-12-02   Albury          7.40         25.10       0.00   
2   2008-12-03   Albury         12.90         25.70       0.00   
3   2008-12-04   Albury          9.20         28.00       0.00   
4   2008-12-05   Albury         17.50         32.30       1.00   
5   2008-12-06   Albury         14.60         29.70       0.20   
6   2008-12-07   Albury         14.30         25.00       0.00   
7   2008-12-08   Albury          7.70         26.70       0.00   
8   2008-12-09   Albury          9.70         31.90       0.00   
9   2008-12-10   Albury         13.10         30.10       1.40   
10  2008-12-11   Albury         13.40         30.40       0.00   
11  2008-12-12   Albury         15.90         21.70       2.64   
12  2008-12-13   Albury         15.90         18.60       2.64   
13  2008-12-14   Albury         12.60         21.00       2.64   
14  2008-12-16   Albury          9.80         27.70       0.00   
15  2008-12-17   Albury         14.10         20.90       0.00   
16  2008-12-18   Albury         13.50         22.90       2.64   
17  2008-12-19   Albury         11.20         22.50       2.64   
18  2008-12-20   Albury          9.80         25.60       0.00   
19  2008-12-21   Albury         11.50         29.30       0.00   

    Wind_gustspeed Winddir_9am Winddir_3pm  Wind_speed9am  Wind_speed3pm  ...  \
0            44.00           W         WNW          20.00          24.00  ...   
1            44.00         NNW         WSW           4.00          22.00  ...   
2            46.00           W         WSW          19.00          26.00  ...   
3            24.00          SE           E          11.00           9.00  ...   
4            41.00         ENE          NW           7.00          20.00  ...   
5            56.00           W           W          19.00          24.00  ...   
6            50.00          SW           W          20.00          24.00  ...   
7            35.00         SSE           W           6.00          17.00  ...   
8            36.84          SE          NW           7.00          28.00  ...   
9            28.00           S         SSE          15.00          11.00  ...   
10           30.00         SSE         ESE          17.00           6.00  ...   
11           31.00          NE         ENE          15.00          13.00  ...   
12           61.00         NNW         NNW          28.00          28.00  ...   
13           44.00           W         SSW          24.00          20.00  ...   
14           50.00          SW         WNW           0.00          22.00  ...   
15           22.00         SSW           E          11.00           9.00  ...   
16           36.84           N         WNW           6.00          20.00  ...   
17           43.00         WSW          SW          24.00          17.00  ...   
18           26.00          SE         NNW          17.00           6.00  ...   
19           24.00          SE          SE           9.00           9.00  ...   

    Humidity_3pm  Pressure_9am  Pressure_3pm  Cloud_9am  cloud3pm  Temp_9am  \
0          22.00       1007.70       1007.10       8.00      1.00     16.90   
1          25.00       1010.60       1007.80       1.00      1.00     17.20   
2          30.00       1007.60       1008.70       1.00      2.00     21.00   
3          16.00       1017.60       1012.80       1.00      1.00     18.10   
4          33.00       1010.80       1006.00       7.00      8.00     17.80   
5          23.00       1009.20       1005.40       1.00      1.00     20.60   
6          19.00       1009.60       1008.20       1.00      1.00     18.10   
7          19.00       1013.40       1010.10       1.00      1.00     16.30   
8           9.00       1008.90       1003.60       1.00      1.00     18.30   
9          27.00       1007.00       1005.70       1.00      1.00     20.10   
10         22.00       1011.80       1008.70       1

In [4]:
df.isnull().sum()

date              0
location          0
minimum_temp      0
maximum_temp      0
rain_fall         0
Wind_gustspeed    0
Winddir_9am       0
Winddir_3pm       0
Wind_speed9am     0
Wind_speed3pm     0
Humidity_9am      0
Humidity_3pm      0
Pressure_9am      0
Pressure_3pm      0
Cloud_9am         0
cloud3pm          0
Temp_9am          0
Temp_3pm          0
Rain_today        0
risk_mm           0
Rain_tomorrow     0
dtype: int64

# Model

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [6]:
X = df.drop("Rain_tomorrow", axis=1)
y = df["Rain_tomorrow"]


In [7]:
label_encoder = LabelEncoder()
categorical_columns = ["location", "Winddir_9am", "Winddir_3pm","date"]


In [8]:
for col in categorical_columns:
    X[col] = label_encoder.fit_transform(X[col])
    

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [11]:
models = {
    'RandomForest': RandomForestClassifier(random_state=42),
    'DecisionTree': DecisionTreeClassifier(random_state=42),
    'LogisticRegression': LogisticRegression(random_state=42),
    'SVM': SVC(random_state=42),
    'KNN': KNeighborsClassifier(),
    'GradientBoosting': GradientBoostingClassifier(random_state=42),
    'NaiveBayes': GaussianNB()
}

for model_name, model in models.items():
    # Label encoding for the target variable
    y_train_encoded = label_encoder.fit_transform(y_train)
    
    # Fit the model
    model.fit(X_train, y_train_encoded)
    
    # Predictions
    y_pred = model.predict(X_test)
    
    # Evaluate the model
    accuracy = accuracy_score(label_encoder.transform(y_test), y_pred)
    conf_matrix = confusion_matrix(label_encoder.transform(y_test), y_pred)
    class_report = classification_report(label_encoder.transform(y_test), y_pred)
    
    # Print the results
    print(f"\nResults for {model_name}:")
    print(f"Accuracy: {accuracy}")
    print(f"Confusion Matrix:\n{conf_matrix}")
    print(f"Classification Report:\n{class_report}")
    


Results for RandomForest:
Accuracy: 0.9998
Confusion Matrix:
[[3889    0]
 [   1 1110]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3889
           1       1.00      1.00      1.00      1111

    accuracy                           1.00      5000
   macro avg       1.00      1.00      1.00      5000
weighted avg       1.00      1.00      1.00      5000


Results for DecisionTree:
Accuracy: 1.0
Confusion Matrix:
[[3889    0]
 [   0 1111]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3889
           1       1.00      1.00      1.00      1111

    accuracy                           1.00      5000
   macro avg       1.00      1.00      1.00      5000
weighted avg       1.00      1.00      1.00      5000


Results for LogisticRegression:
Accuracy: 0.946
Confusion Matrix:
[[3756  133]
 [ 137  974]]
Classification Report:
        

In [12]:
def check_overfitting(model, X_train, y_train, X_test, y_test, cv=5):
    # Calculate training accuracy using cross-validation
    train_accuracy = np.mean(cross_val_score(model, X_train, y_train, cv=cv))
    
    # Fit the model to the entire training set
    model.fit(X_train, y_train)
    
    # Calculate testing accuracy
    test_accuracy = model.score(X_test, label_encoder.transform(y_test))
    
    print(f"Training Accuracy: {train_accuracy}")
    print(f"Testing Accuracy: {test_accuracy}")
    
    # Compare training and testing accuracy
    if train_accuracy > test_accuracy:
        print("Risk of Overfitting: Training accuracy is higher than testing accuracy.")
    elif train_accuracy < test_accuracy:
        print("Risk of Underfitting: Training accuracy is lower than testing accuracy.")
    else:
        print("The model is well-fit.")


In [13]:
from sklearn.model_selection import cross_val_score
import numpy as np

# Function to check overfitting or underfitting
def check_overfitting(model_name, model, X_train, y_train, X_test, y_test, cv=5):
    # Calculate training accuracy using cross-validation
    train_accuracy = np.mean(cross_val_score(model, X_train, y_train, cv=cv))
    
    # Fit the model to the entire training set
    model.fit(X_train, y_train)
    
    # Calculate testing accuracy
    y_test_encoded = label_encoder.transform(y_test)
    test_accuracy = model.score(X_test, y_test_encoded)
    
    print(f"\nResults for {model_name}:")
    print(f"Training Accuracy: {train_accuracy}")
    print(f"Testing Accuracy: {test_accuracy}")
    
    # Compare training and testing accuracy
    if train_accuracy > test_accuracy:
        print("Risk of Overfitting: Training accuracy is higher than testing accuracy.")
    elif train_accuracy < test_accuracy:
        print("Risk of Underfitting: Training accuracy is lower than testing accuracy.")

# Example usage for all models
for model_name, model in models.items():
    check_overfitting(model_name, model, X_train, label_encoder.transform(y_train), X_test, y_test)
    


Results for RandomForest:
Training Accuracy: 0.9999500000000001
Testing Accuracy: 0.9998
Risk of Overfitting: Training accuracy is higher than testing accuracy.

Results for DecisionTree:
Training Accuracy: 0.9999500000000001
Testing Accuracy: 1.0
Risk of Underfitting: Training accuracy is lower than testing accuracy.

Results for LogisticRegression:
Training Accuracy: 0.9368000000000001
Testing Accuracy: 0.946
Risk of Underfitting: Training accuracy is lower than testing accuracy.

Results for SVM:
Training Accuracy: 0.7758
Testing Accuracy: 0.7778
Risk of Underfitting: Training accuracy is lower than testing accuracy.

Results for KNN:
Training Accuracy: 0.82455
Testing Accuracy: 0.8224
Risk of Overfitting: Training accuracy is higher than testing accuracy.

Results for GradientBoosting:
Training Accuracy: 0.9999500000000001
Testing Accuracy: 1.0
Risk of Underfitting: Training accuracy is lower than testing accuracy.

Results for NaiveBayes:
Training Accuracy: 0.9805499999999998
Tes

# Tuning and pipline

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline


In [15]:
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
    ('classifier', RandomForestClassifier(random_state=42))
])


In [16]:
param_grid = {
    'imputer__strategy': ['mean', 'median'],  # Reduce options for demonstration
    'classifier__n_estimators': [50, 100],
    'classifier__max_depth': [None, 10],
    'classifier__min_samples_split': [2, 5],
    'classifier__min_samples_leaf': [1, 2],
    'classifier__bootstrap': [True, False]
}

In [17]:
grid_search = GridSearchCV(pipeline, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, label_encoder.transform(y_train))

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('imputer', SimpleImputer()),
                                       ('scaler', StandardScaler()),
                                       ('classifier',
                                        RandomForestClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'classifier__bootstrap': [True, False],
                         'classifier__max_depth': [None, 10],
                         'classifier__min_samples_leaf': [1, 2],
                         'classifier__min_samples_split': [2, 5],
                         'classifier__n_estimators': [50, 100],
                         'imputer__strategy': ['mean', 'median']},
             scoring='accuracy')

In [18]:
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

In [19]:
y_pred_best = best_model.predict(X_test)
accuracy_best = accuracy_score(label_encoder.transform(y_test), y_pred_best)
conf_matrix_best = confusion_matrix(label_encoder.transform(y_test), y_pred_best)
class_report_best = classification_report(label_encoder.transform(y_test), y_pred_best)

In [20]:
print("Best Model Results:")
print(f"Best Parameters: {best_params}")
print(f"Best Accuracy: {accuracy_best}")
print(f"Confusion Matrix:\n{conf_matrix_best}")
print(f"Classification Report:\n{class_report_best}")

Best Model Results:
Best Parameters: {'classifier__bootstrap': True, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 50, 'imputer__strategy': 'mean'}
Best Accuracy: 0.9998
Confusion Matrix:
[[3889    0]
 [   1 1110]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3889
           1       1.00      1.00      1.00      1111

    accuracy                           1.00      5000
   macro avg       1.00      1.00      1.00      5000
weighted avg       1.00      1.00      1.00      5000



In [21]:
results_df = pd.DataFrame(columns=['Model', 'Testing Accuracy'])

# Function to check overfitting or underfitting
def check_overfitting(model_name, model, X_train, y_train, X_test, y_test, cv=5):
    # Calculate training accuracy using cross-validation
    train_accuracy = np.mean(cross_val_score(model, X_train, y_train, cv=cv))
    
    # Fit the model to the entire training set
    model.fit(X_train, y_train)
    
    # Calculate testing accuracy
    y_test_encoded = label_encoder.transform(y_test)
    test_accuracy = model.score(X_test, y_test_encoded)
    
    # Append results to the DataFrame
    results_df.loc[len(results_df)] = [model_name, test_accuracy]

# Example usage for all models
for model_name, model in models.items():
    check_overfitting(model_name, model, X_train, label_encoder.transform(y_train), X_test, y_test)

# Display the results DataFrame
results_df.sort_values(by='Testing Accuracy', ascending=False, inplace=True)
print(results_df)


                Model  Testing Accuracy
1        DecisionTree              1.00
5    GradientBoosting              1.00
0        RandomForest              1.00
6          NaiveBayes              0.98
2  LogisticRegression              0.95
4                 KNN              0.82
3                 SVM              0.78
